#!/bin/sh
cd "$(dirname $0)"


# ---
# Defaults variables
# ---

make_full_log=
debug=
optimize=y
objdir=build
outdir=.
cflags=
ldflags=

# ---
# Help message
# ---

usage() {
cat <<EOF
Usage: $0 [OPTION]
Defaults for the options are specified in brackets.
General options:
  --help                   display this help and exit
  --make-full-log          display full commands while making
Build options:
  --debug                  enable debug mode
  --optimize-disable       disable optimization
  --objdir=OBJDIR          directory for all object (default: ./build)
  --outdir=OUTDIR          directory for all output executable (default : ./bin)
Other tweaks:
  CFLAGS=CFLAGS            some more compilation flags
  LDFLAGS=LDFLAGS          some more linker flags
Report bugs to ${maintainer}.
EOF
exit 0
}

# ---
# Check for help
# ---

for arg ; do case "$arg" in
--help|-h) usage ;;
esac; done


# ---
# Parse arguments
# ---

for arg ; do case "$arg" in
--make-full-log) make_full_log=y ;;
--debug) debug=y ;;
--optimize-disable) optimize= ;;
--objdir=*) objdir="${arg#*=}" ;;
--outdir=*) outdir="${arg#*=}" ;;
--cflags=*) cflags="${arg#*=}" ;;
--ldflags=*) ldflags="${arg#*=}" ;;
*) echo "Unknown option: ${arg#*=}";exit 1 ;;
esac; done

# ---
# Write Makefile.cfg
# ---

# Clean after

make mrproper MAKE_FULL_LOG=y 1>/dev/null 2>/dev/null

# Write

exec 3>&1 1>Makefile.cfg
cat <<EOF
#!/usr/bin/make -f
#******************************************************************************#
# Makefile configuration generated by ./configure                              #
#******************************************************************************#
# Log configuration
MAKE_FULL_LOG = $make_full_log
# Build options
DEBUG := $debug
OPTIMIZE := $optimize
OBJDIR := $objdir
OUTDIR := $outdir
# Other tweaks
CMOREFLAGS := $cflags
LDMOREFLAGS := $ldflags
# End of file
EOF
exec 1>&3 3>&-

# Make it executable

chmod +x Makefile.cfg

# Print success message

echo "Configuration loaded, you can make now"

# End of file

